title: Paolo Libenzio Brignoli
#logo /relative path in github
#description - text below image
email: paolo.brignoli at wur dot nl
logo: /images/IMG_1721.png
show downloads: false
theme: jekyll-theme-minimal
